### PR TITLE
Eliminate extra and pedantic warnings

### PR DESCRIPTION
**Pull request by TheCoconutChef**
Enforce all warnings as error

## Why?

[Vendoring](https://github.com/friendlyanon/cmake-init-fetchcontent) is the practice of

> pulling the source code of other projects into your own

This is precisely what CMake features such as [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html)
and the [CPM project](https://github.com/cpm-cmake/CPM.cmake) do.

While convenient and seemingly well suited for header only libraries such as zug, vendoring has the disadvantage that:

> Even if something is easy to vendor, because everything happens in a single build, the vendored project will inherit your flags, which could cause errors in sources compiled from the vendored project if you are using a warnings-as-errors flag.

Thus, projects which wish to be easy to vendor ought to strive to be maximally restrictive with respect to their flags.

By adding `-Wextra`, `-Wpedantic` and `-Werror`, we increase vendoring friendliness.

**N.B.** This issue is well knowned to the cmake maitainers and is explicitly addressed [here](https://gitlab.kitware.com/cmake/cmake/-/issues/18040), i.e. it will be fixed on the cmake side in version 3.25 by allowing the importing project to stipulate that code pulled through FetchContent should be treated as a system include.

However, we can't assume everyone will switch to cmake 3.25.

### CODE REVIEW

**Review by arximboldi — APPROVED** [review]
I personally do not like vendoring and "chasing warnings" like that because there are endless warnings compilers give, sometimes contradictory, and some of them are even useless (particularly "unused parameter" warnings). Compilers provide `-isystem` and alike for a reason and the right thing is to use them.

But in this case all the changes seem quite sensible (excepting the "unused parameter" warning, I'd solve it instead by just removing the name from the parameter, but I am aware some other comlpilers then warn about "unnamed parameter" :angry: ) so I'm happy to accept these changes :smile:

**Comment by arximboldi** [comment]
Ohhh, here we go... the build fails :sweat_smile:

**Comment by TheCoconutChef** [comment]
I removed the `ZUG_UNUSED` macro, removed the `-Wextra`, `-Wpedantic` level warnings (only keeping `-Werror`, and ran the tests on both gcc and clang.

**Comment by arximboldi** [comment]
Thank you a lot! Tasty Coconut recipe here!

**Pull request merged**
