### PR TITLE
Use Catch2 as installed

### PR DESCRIPTION
**Pull request by pinotree**
When building the tests, require and use Catch2 as installed in the system, rather than using an old embedded copy of it. This way, there is no risk it will stop working with newer versions of glibc/gcc/etc.

This also changes the nix packaging to disable tests & examples: they are not used in any way, so better disable them to avoid requiring bits only needed for them.

Fixes: #35

### CODE REVIEW

**Comment by arximboldi** [comment]
Oh... it looks like the tests are failing. It's unrelated: `cachix-action` and `install-nix-action` need to be upgraded to the latest version. Do you want to do it yourself?

**Comment by pinotree** [comment]
> It's unrelated: `cachix-action` and `install-nix-action` need to be upgraded to the latest version. Do you want to do it yourself?

Let's try: #37

**Comment by pinotree** [comment]
Unfortunately I'm a bit loss at the nix failures here; it'd looks like the nix environment is too old, and it doesn't known/have catch2.

**Comment by arximboldi** [comment]
Hmmm, yes this requires upgrading the `nixpkgs` which is pinned at the top of `shell.nix`...

**Comment by arximboldi** [comment]
Fixed in #38

**Pull request merged**
